### ISSUE TITLE
Don't get how this works with regards to config and users ...

### ISSUE THREAD

**Issue by Kramerican** [bruhs/caddy-service#8]
Howdy,

On Ubuntu 16.04

I'd like to run caddy as an unprivileged user. If I add a caddy user and add a Caddyfile to /home/caddy/Caddyfile, I can easily start caddy as that user and point it to my config. I'm just doing the old nohup trick now, but I'd feel better if Caddy was a service and would start on boot.

However, I don't quite get how I can do this - this plugin seems to be what I want, but I've tried many a command without sucess (essentially, I can start the service, but can't figure out how to tell it to start as caddy user nor how to point it to my config file)

I apologize beforehand for any n00bish-ness here :)

**Comment by tobya** [comment]
To point to the config file the best thing to do is to use the `-conf`directive when creating the service

    caddy -service install -name caddyService -conf path/to/Caddyfile -log path/to/log

As for specifiying user, I'm not sure.

**Comment by fabiofcferreira** [comment]
Hi! 

We created caddy-service because we run Windows on our machines, so we had to re-execute every single time we made any change to a plugin we were developing.
Even though I'm one of the creators, I honestly prefer to use _systemd_ on Linux setups.

Check [this out](https://github.com/mholt/caddy/tree/master/dist/init/linux-systemd)

Thanks :smile:
