### ISSUE TITLE
Add "status" -service command

### ISSUE THREAD

**Issue by aadrian** [bruhs/caddy-service#9]
Please add a "-service status" command.

Thank you.

**Comment by tobya** [comment]
@aadrian What values would you see the status command returning?

**Comment by aadrian** [comment]
@tobya the usual with services, e.g. :
 - `installed and running`, maybe +` since xx days`
 - `installed and stopped`, maybe +` last time started xx days ago`
 - `not installed`
 - maybe `previous error: xxxx` if it can't run for a reason.

**Comment by hacdias** [comment]
I'm not much available to do this right now, but I hope @fabiofcferreira can handle this. You can also contribute if you want 😄

**Comment by fabiofcferreira** [comment]
You can check the last time Caddy was started and stopped if you use logs directive in Caddy. We think it is not a very good idea to create it ourselves (reinventing the wheel) since Matt's already done it.

We've added the `caddy -service status` command. You can check if service is installed, running or stopped.

Thanks for contribution. 👍
